
package com.xdev.jcon_19_i18n.ui;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "viewtimezone", layout = MainContainer.class)
public class ViewTimezones extends VerticalLayout
{

	/**
	 *
	 */
	public ViewTimezones()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.setClassName("my-view my-view3");
		
		this.setSizeFull();
	} // </generated-code>
	
}
