
package com.xdev.jcon_19_i18n.ui;

import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.details.Details;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.splitlayout.SplitLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.Route;


@Route(value = "viewRTL", layout = MainContainer.class)
public class ViewRTL extends VerticalLayout
{
	
	/**
	 *
	 */
	public ViewRTL()
	{
		super();
		this.initUI();
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #button}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button_onClick(final ClickEvent<Button> event)
	{
		this.getClassNames().add("rtl-support");
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #button2}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button2_onClick(final ClickEvent<Button> event)
	{
		this.getClassNames().remove("rtl-support");
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.horizontalLayout = new HorizontalLayout();
		this.button           = new Button();
		this.button2          = new Button();
		this.textField        = new TextField();
		this.label            = new Label();
		this.splitLayout      = new SplitLayout();
		this.verticalLayout   = new VerticalLayout();
		this.details          = new Details();
		this.verticalLayout2  = new VerticalLayout();

		this.button.setText("RTL aktivieren");
		this.button2.setText("RTL deaktivieren");
		this.label.setText("Ich bin ein Text, von Rechts nach Links geschrieben");
		this.details.setSummaryText("Detail 1");
		this.details.setOpened(true);

		this.button.setSizeUndefined();
		this.button2.setSizeUndefined();
		this.horizontalLayout.add(this.button, this.button2);
		this.verticalLayout.add(this.details);
		this.verticalLayout.setHorizontalComponentAlignment(FlexComponent.Alignment.STRETCH, this.details);
		this.splitLayout.addToPrimary(this.verticalLayout);
		this.splitLayout.addToSecondary(this.verticalLayout2);
		this.splitLayout.setSplitterPosition(20.0);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.textField.setSizeUndefined();
		this.label.setSizeUndefined();
		this.splitLayout.setSizeFull();
		this.add(this.horizontalLayout, this.textField, this.label, this.splitLayout);
		this.setFlexGrow(1.0, this.splitLayout);
		this.setSizeFull();

		this.button.addClickListener(this::button_onClick);
		this.button2.addClickListener(this::button2_onClick);
	} // </generated-code>
	
	// <generated-code name="variables">
	private Button           button, button2;
	private Details          details;
	private SplitLayout      splitLayout;
	private HorizontalLayout horizontalLayout;
	private VerticalLayout   verticalLayout, verticalLayout2;
	private Label            label;
	private TextField        textField;
	// </generated-code>

}
