
package com.xdev.jcon_19_i18n.ui;

import com.rapidclipse.framework.server.resources.StringResourceUtils;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.router.Route;


@Route(value = "i18nview", layout = MainContainer.class)
public class ViewManuallyI18N extends VerticalLayout
{
	
	/**
	 *
	 */
	public ViewManuallyI18N()
	{
		super();
		this.initUI();
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #button}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button_onClick(final ClickEvent<Button> event)
	{
		this.textArea.setValue(StringResourceUtils.optLocalizeString("{$message.warning.delete}", this));
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.button   = new Button();
		this.textArea = new TextArea();

		this.setClassName("my-view my-view3");
		this.button.setText("Meldung ausgeben");

		this.button.setWidthFull();
		this.button.setHeight(null);
		this.textArea.setWidthFull();
		this.textArea.setHeight("200px");
		this.add(this.button, this.textArea);
		this.setSizeFull();

		this.button.addClickListener(this::button_onClick);
	} // </generated-code>
	
	// <generated-code name="variables">
	private Button   button;
	private TextArea textArea;
	// </generated-code>

}
